import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <aside>
        <div className={styles.menu}>
          <span>
            <img src="../images/logo.jpg" alt=""/>
          </span>
          <p>Home</p>
          <p>Obras v</p>
          <p>Contato</p>
        </div>
      </aside>

      <div className={styles.principal}></div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Feito por {' '}
          <span className={styles.logo}>
          
          </span>
        </a>
      </footer>
    </div>
  )
}
